# By specifying the types as a "LoadBalancer" Kubernetes Engine will create an
# External Http Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: sandesh-weatherapp
spec:
  type: LoadBalancer
  selector:
    app: sandesh-weatherapp
  ports: 
  - port: 80
    targetPort: 3000